### ISSUE TITLE
Card transparency

### ISSUE THREAD

**Issue by bwestrek** [3ative/3ative-blue-theme#1]
Hi,

Since the installation of Home Assistant to version 0.113 the card transparency of this theme does not work anymore. I've tested it with another theme that includes transparency and it works.

Could you take a look at it. Thank you in advance.

**Comment by 3ative** [comment]
Working on that now, an update will available soon.

**Comment by 3ative** [comment]
Done, please update. 👍

**Comment by bwestrek** [comment]
Brilliant work👍

**Comment by 3ative** [comment]
@bwestrek Thanks. If you find anything else, please feel free to open another issue. Cheers!
